package domain.values;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import domain.Project;
import domain.Sprite;
import domain.models.interfaces.Valuable;
import ui.components.SpritePanel;
import ui.renderers.LiteralRenderer.LiteralRenderable;
import ui.renderers.SimpleBlockRenderer;
import ui.renderers.SimpleBlockRenderer.SimpleRenderable;

/**
 * Represents a sprite or global variable
 * @param <T>
 */
public class Variable<T> extends AbstractLiteral<T> implements SimpleRenderable {
	
	/**
	 * A value pointer to create multiple instances of the same variable (for renderer purposes)
	 * @param <T>
	 */
	public static class Value<T> implements Serializable {
		private static final long serialVersionUID = -6209168702389374905L;
		
		public T value;
		public T initialValue;
		private Value(T value) {
			this.value = value;
			this.initialValue = value;
		}
		public Value(T value, T initialValue) {
			this.value = value;
			this.initialValue = initialValue;
		}
		
		
	}

	private static final long serialVersionUID = 6146036704484981438L;
	
	/**
	 * Creates a global variable of the desired type with the desired initial value
	 * @param <T> Type of the variable
	 * @param name Unique name of the variable
	 * @param value Initial value of the variable
	 * @return
	 */
	public static <T> Variable<T> createGlobalVariable(String name, T value) {
		return createVariable(null, name, value);
	}
	
	/**
	 * Create a local variable with the desired name and the default value
	 * @param <T> Type of the variable
	 * @param s Sprite where the variable is stored
	 * @param name name of the variable
	 * @param value initial value of the variable
	 * @return
	 */
	public static <T> Variable<T> createVariable(Sprite s, String name, T value) {
		return createVariable(s, name, value, false);
	}
	/**
	 * Create a local variable with the desired name and the default value with the option of creating it native (not deletable)
	 * @param <T> Type of the variable
	 * @param s Sprite where the variable is stored
	 * @param name name of the variable
	 * @param value initial value of the variable
	 * @param whether it must be inmune to variable deleting
	 * @return
	 */
	public static <T> Variable<T> createVariable(Sprite s, String name, T value, boolean nat) {
		Variable<T> var = new Variable<T>(name, value, s, nat);
		Project.getActiveProject().registerVariable(s, name, var);
		return var;
	}
	
	public static Variable<?> getGlobalVariable(String name) {
		return getVariable(null, name);
	}
	
	public static Variable<?> getVariable(Sprite s, String name) {
		return Project.getActiveProject().getVariable(s, name);
	}
	
	public static List<Variable<?>> getVisibleVariables() {
		List<Variable<?>> output = new ArrayList<>(Project.getActiveProject().getVariablesOf(null).values());
		output.addAll(Project.getActiveProject().getVariablesOf(SpritePanel.getSprite()).values());
		return output;
	}
	
	public AbstractLiteral<T> create(Sprite s) {
		return new Variable<>(name, value(), sprite, nat);
	}
	
	
	public final String name;
	private boolean nat;
	public final Sprite sprite;
	private SimpleBlockRenderer sbr;
	private Value<T> value;
	
	private Variable(String name, T value, Sprite sprite, boolean isNative) {
		super(value, null);
		this.name = name;
		this.value = new Value<>(value);
		this.sprite = sprite;
		this.nat = isNative;
		this.sbr = new SimpleBlockRenderer(this);
	}
	
	private Variable(String name, Value<T> value, Sprite sprite, boolean isNative) {
		super(value.value, null);
		this.name = name;
		this.value = value;
		this.sprite = sprite;
		this.nat = isNative;
		this.sbr = new SimpleBlockRenderer(this);
	}
	
	@Override
	public SimpleBlockRenderer getRenderer() {
		return sbr;
	}
	
	/**
	 * Native variables are those that are generated by the sprite itself and therefore not deletable
	 * @return
	 */
	public boolean isNative() {
		return nat;
	}
	
	public boolean isGlobal() {
		return Project.getActiveProject().getVariable(null, this.name) != null;
	}
	
	public Variable<?> setValue(T value) {
		this.value.value = value;
		return this;
	}
	
	public Class<?> getValueClass() {
		return value.getClass();
	}
	
	public String toString() {
		return (sprite==null?"GlobalVariables":sprite.getName()) +"."+name; 
	}
	
	@Override
	public T value() {
		return value.value;
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public void setValue(Object object, boolean update) {
		this.value.value = (T)object;
		if(update)
			this.value.initialValue = (T)object;
		super.setValue(object, update);
	}
	
	@Override
	public T initialValue() {
		return value.initialValue;
	}
	@Override
	public String getCode() {
		return nat?"this.get" + this.name.substring(0, 1).toUpperCase() + this.name.substring(1) + "()" : this.name;
	}
	
	public String getInitialization() {
		return NumberHelper.getEquivalent(this.initialValue().getClass()).getSimpleName() + " " + name + " = " + (this.initialValue() instanceof String? "\"" + this.initialValue() + "\"" : this.initialValue()) + ";";
	}
	
	/**
	 * Gets the line representing the definition of the variable
	 * e.g: String varname = "defaultValue";
	 * @return
	 */
	public String getDefinition() {
		return value.value.getClass().getName() + " " + name + " = " + ((initialValue() instanceof String)?'"'+initialValue().toString()+"'":initialValue())+";";
	}
	@Override
	public void getImports(Set<String> imports) {}
	
	@Override
	public boolean isEmpty() {
		return false;
	}
	@SuppressWarnings("unchecked")
	@Override
	public void setValue(String str) {
		switch(initialValue()) {
			case String s:
				this.setValue((T)str, true);
				break;
			case Number n:
				this.setValue((T)NumberHelper.parse(str, n.getClass()), true);
				break;
			case Boolean b:
				this.setValue((T)(Boolean)Boolean.parseBoolean(str), true);
				break;
			default:
				
		}
			
	}
	@Override
	public Valuable<?> getVariableAt(int i) {return null;} // N/A
	public Valuable<?>[] getAllVariables() {return new Valuable[0];} // N/A
	public void setVariableAt(int i, Valuable<?> v) {} // N/A
	public void removeVariableAt(int i) {} // N/A
	public LiteralRenderable<?> removeVariable(Valuable<?> v) {return null;} // N/A
	public void replaceVariable(Valuable<?> old, Valuable<?> newValue) {} // N/A
	
	@Override
	public boolean isAplicable(Valuable<?> v) {
		return false;
	}
	@Override
	public String getTitle() {
		return name;
	}
	@Override
	public BlockCategory getCategory() {
		return switch(value()) {
			case Number n ->  BlockCategory.NUMBER_VARIABLE;
			case Boolean b -> BlockCategory.BOOLEAN_VARIABLE;
			default -> BlockCategory.STRING_VARIABLE;
		};
	}

}
