package domain.values;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import domain.Project;
import domain.Sprite;
import domain.models.interfaces.Valuable;
import ui.components.SpritePanel;
import ui.renderers.LiteralRenderer.LiteralRenderable;
import ui.renderers.SimpleBlockRenderer;
import ui.renderers.SimpleBlockRenderer.SimpleRenderable;

/**
 * Represents a sprite or global variable
 * @param <T>
 */
public class Variable<T> extends AbstractLiteral<T> implements SimpleRenderable {

	private static final long serialVersionUID = 6146036704484981438L;
	
	/**
	 * Creates a global variable of the desired type with the desired initial value
	 * @param <T> Type of the variable
	 * @param name Unique name of the variable
	 * @param value Initial value of the variable
	 * @return
	 */
	public static <T> Variable<T> createGlobalVariable(String name, T value) {
		return createVariable(null, name, value);
	}
	
	/**
	 * Create a local variable with the desired name and the default value
	 * @param <T> Type of the variable
	 * @param s Sprite where the variable is stored
	 * @param name name of the variable
	 * @param value initial value of the variable
	 * @return
	 */
	public static <T> Variable<T> createVariable(Sprite s, String name, T value) {
		return createVariable(s, name, value, false);
	}
	/**
	 * Create a local variable with the desired name and the default value with the option of creating it native (not deletable)
	 * @param <T> Type of the variable
	 * @param s Sprite where the variable is stored
	 * @param name name of the variable
	 * @param value initial value of the variable
	 * @param whether it must be inmune to variable deleting
	 * @return
	 */
	public static <T> Variable<T> createVariable(Sprite s, String name, T value, boolean nat) {
		Variable<T> var = new Variable<T>(name, value, s, nat);
		Project.getActiveProject().registerVariable(s, name, var);
		return var;
	}
	
	public static Variable<?> getGlobalVariable(String name) {
		return getVariable(null, name);
	}
	
	public static Variable<?> getVariable(Sprite s, String name) {
		return Project.getActiveProject().getVariable(s, name);
	}
	
	public static List<Variable<?>> getVisibleVariables() {
		List<Variable<?>> output = new ArrayList<>(Project.getActiveProject().getVariablesOf(null).values());
		output.addAll(Project.getActiveProject().getVariablesOf(SpritePanel.getSprite()).values());
		return output;
	}
	
	
	public final String name;
	private boolean nat;
	public final Sprite sprite;
	
	private Variable(String name, T value, Sprite sprite, boolean isNative) {
		super(value, null);
		this.name = name;
		this.sprite = sprite;
		this.nat = isNative;
	}
	@Override
	public SimpleBlockRenderer getRenderer() {
		return new SimpleBlockRenderer(this);
	}
	
	/**
	 * Native variables are those that are generated by the sprite itself and therefore not deletable
	 * @return
	 */
	public boolean isNative() {
		return nat;
	}
	
	public boolean isGlobal() {
		return Project.getActiveProject().getVariable(null, this.name) != null;
	}
	
	public Variable<?> setValue(T value) {
		this.value = value;
		return this;
	}
	
	public Class<?> getValueClass() {
		return value.getClass();
	}
	
	public String toString() {
		return (sprite==null?"GlobalVariables":sprite.getName()) +"."+name; 
	}
	@Override
	public T value() {
		return value;
	}
	@Override
	public String getCode() {
		return this.name;
	}
	
	/**
	 * Gets the line representing the definition of the variable
	 * e.g: String varname = "defaultValue";
	 * @return
	 */
	public String getDefinition() {
		return value.getClass().getName() + " " + name + " = " + ((initialValue() instanceof String)?'"'+initialValue().toString()+"'":initialValue())+";";
	}
	@Override
	public void getImports(Set<String> imports) {}
	
	@Override
	public boolean isEmpty() {
		return false;
	}
	@SuppressWarnings("unchecked")
	@Override
	public void setValue(String str) {
		if(initialValue() instanceof String)
			this.setValue((T)str, true);
		else if(initialValue() instanceof Number)
			this.setValue((T)NumberHelper.parse(str, (Class<? extends Number>) value.getClass()), true);
		else if(initialValue() instanceof Boolean)
			this.setValue((T)(Boolean)Boolean.parseBoolean(str), true);
	}
	@Override
	public Valuable<?> getVariableAt(int i) {return null;} // N/A
	public Valuable<?>[] getAllVariables() {return new Valuable[0];} // N/A
	public void setVariableAt(int i, Valuable<?> v) {} // N/A
	public void removeVariableAt(int i) {} // N/A
	public LiteralRenderable<?> removeVariable(Valuable<?> v) {return null;} // N/A
	public void replaceVariable(Valuable<?> old, Valuable<?> newValue) {} // N/A
	
	@Override
	public boolean isAplicable(Valuable<?> v) {
		return false;
	}
	@Override
	public String getTitle() {
		return name;
	}
	@Override
	public BlockCategory getCategory() {
		if(value() instanceof Number)
			return BlockCategory.NUMBER_VARIABLE;
		else if(value() instanceof Boolean)
			return BlockCategory.BOOLEAN_VARIABLE;
		else
			return BlockCategory.STRING_VARIABLE;
	}

}
